version: '3.8'

services:
  app:
    build:
      context: "./"
      dockerfile: Dockerfile
      args:
        USER_ID: '${WWWUSER:-1000}'
        GROUP_ID: '${WWWGROUP:-1000}'
        USER: '${USER:-whoami}'
    container_name: contribuyentes-app
    restart: always
    working_dir: /var/www/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../:/var/www 
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - my-network
    links:
      - nginx
    
  nginx:
    image: nginx:1.19-alpine
    container_name: contribuyentes-nginx
    restart: always
    ports:
      - "80:80"
    
    volumes: 
      - ../:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     
    networks:
      - my-network
    links:
     - db
 
 
  
  db:
    container_name: contribuyentes-db
    image: mysql:8.0
    volumes:
     #- ./storage/mysql:/var/lib/mysql
    - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - my-network

volumes:
  mysql_data:
networks:
  my-network:
   